### ISSUE TITLE
Please do not hard pin btlewrap to this very outdated version

### ISSUE THREAD

**Issue by onkelbeh** [basnijholt/miflora#163]
Please do not hard pin btlewrap to this very outdated version

**Comment by basnijholt** [comment]
Did you test if it works with newer versions?

If so, I will happily accept a PR :)

**Comment by onkelbeh** [comment]
Sorry, I can't, don't have the hardware.
I just maintain it for completeness of [Home Assistant for Gentoo](https://github.com/onkelbeh/HomeAssistantRepository). I won't send an untested PR.

**Comment by cdce8p** [comment]
Any updates? Just from looking at the release notes and diff, it seems to be compatible. The only potential breakage mentioned is that `btlewrap` unpinned their requirements too.
https://github.com/ChristianKuehnel/btlewrap/releases/tag/v0.1.0
https://github.com/ChristianKuehnel/btlewrap/compare/v0.0.10...v0.1.0

This change would help us at Home Assistant resolve a dependency conflict that is currently one of the things holding back our pip upgrade to the new resolver.

Something like this would very likely work.
```
btlewrap>=0.0.10,<0.11
```

**Comment by basnijholt** [comment]
If anyone can test this I'll merge and release (from phone). Currently AFK until February.

**Comment by cdce8p** [comment]
@basnijholt Thanks for the reply! I'm unable to test it myself unfortunately. I did however check the compare diff. From what I can tell version `0.1.0` didn't change any existing APIs. Thus I think it's reasonable to assume it will work. I've opened #168 for the dependency bump.

**Comment by basnijholt** [comment]
I released v0.7.2 without the strict pinning.

**Comment by cdce8p** [comment]
> I released v0.7.2 without the strict pinning.

Thanks @basnijholt!
